"""Tiny, dependency-free reader/writer for SolveSpace ``.slvs`` files.

The format (``src/file.cpp`` in the SolveSpace source) is plain text after a
three-byte magic prefix::

    B1 B2 B3 "SolveSpaceREVa" \n

Those three bytes are *raw* ``0xB1 0xB2 0xB3``, not UTF-8.  An editor that
re-saves the file as UTF-8 turns them into ``C2 B1 C2 B2 C2 B3`` and SolveSpace
then reports "Unrecognized data in file".  Everything in this module therefore
works on bytes, and :func:`fix_magic` repairs that exact corruption.

Records are ``Key=Value`` lines committed by a bare marker line
(``AddGroup``, ``AddParam``, ``AddRequest``, ``AddEntity``, ``AddConstraint``,
``AddStyle``).  :func:`parse` returns those records as dictionaries so the
checks in ``tools/check.py`` can read solved parameter values straight out of a
regenerated file.

SPDX-License-Identifier: CC-BY-SA-4.0
"""
from __future__ import annotations

import sys
from pathlib import Path

MAGIC_RAW = b"\xb1\xb2\xb3SolveSpaceREVa"
MAGIC_UTF8 = "±²³SolveSpaceREVa".encode("utf-8")  # C2 B1 C2 B2 C2 B3 ...
MARKERS = ("AddGroup", "AddParam", "AddRequest", "AddEntity", "AddConstraint", "AddStyle")


def read_bytes(path: Path) -> bytes:
    return Path(path).read_bytes()


def has_raw_magic(data: bytes) -> bool:
    return data.startswith(MAGIC_RAW)


def has_utf8_magic(data: bytes) -> bool:
    return data.startswith(MAGIC_UTF8)


def fix_magic(path: Path) -> bool:
    """Rewrite a UTF-8-mangled header back to the raw bytes.

    Returns True if the file was changed.  Also normalises CRLF to LF, which
    SolveSpace tolerates on read but never writes.
    """
    path = Path(path)
    data = path.read_bytes()
    changed = False
    if has_utf8_magic(data):
        data = MAGIC_RAW + data[len(MAGIC_UTF8):]
        changed = True
    if b"\r\n" in data:
        data = data.replace(b"\r\n", b"\n")
        changed = True
    if changed:
        path.write_bytes(data)
    return changed


def parse(path: Path) -> list[dict]:
    """Return the records of a ``.slvs`` file.

    Each record is a dict with ``_kind`` set to the marker that committed it
    (e.g. ``"AddParam"``) plus the ``Key=Value`` pairs, values as strings.
    The multi-line ``Group.remap={ ... }`` block is kept as a list of lines.
    """
    data = Path(path).read_bytes()
    if not has_raw_magic(data):
        raise ValueError(f"{path}: missing raw .slvs magic (run fix_magic)")
    text = data[len(MAGIC_RAW):].decode("latin-1")
    records: list[dict] = []
    cur: dict = {}
    in_remap = False
    for raw in text.split("\n"):
        line = raw.rstrip("\r")
        if in_remap:
            if line.strip() == "}":
                in_remap = False
            else:
                cur.setdefault("Group.remap", []).append(line.strip())
            continue
        if not line.strip():
            continue
        if line in MARKERS:
            cur["_kind"] = line
            records.append(cur)
            cur = {}
            continue
        if line.startswith(("Triangle ", "Surface ", "SCtrl ", "TrimBy ", "Curve ",
                            "CCtrl ", "CurvePt ")) or line in ("AddSurface", "AddCurve"):
            continue  # cached mesh / shell, regenerated by SolveSpace
        if "=" in line:
            key, val = line.split("=", 1)
            if key == "Group.remap" and val == "{":
                in_remap = True
                cur.setdefault("Group.remap", [])
                continue
            cur[key] = val
    return records


def params(path: Path) -> dict[str, float]:
    """Map ``Param.h.v.`` handle (hex string) to its solved value."""
    out: dict[str, float] = {}
    for rec in parse(path):
        if rec.get("_kind") == "AddParam":
            out[rec["Param.h.v."]] = float(rec.get("Param.val", "0"))
    return out


def entities(path: Path) -> dict[str, dict]:
    return {r["Entity.h.v"]: r for r in parse(path) if r.get("_kind") == "AddEntity"}


def constraints(path: Path) -> dict[str, dict]:
    return {r["Constraint.h.v"]: r for r in parse(path) if r.get("_kind") == "AddConstraint"}


def act_point(path_or_entities, handle: str) -> tuple[float, float, float]:
    """Solved position of a point entity, from ``Entity.actPoint.{x,y,z}``."""
    ents = path_or_entities if isinstance(path_or_entities, dict) else entities(path_or_entities)
    e = ents[handle]
    return (float(e.get("Entity.actPoint.x", 0)),
            float(e.get("Entity.actPoint.y", 0)),
            float(e.get("Entity.actPoint.z", 0)))


def main(argv: list[str]) -> int:
    """``python slvs.py fix FILE...`` / ``python slvs.py check FILE...``"""
    if len(argv) < 2 or argv[0] not in ("fix", "check"):
        print(__doc__)
        return 2
    bad = 0
    for p in argv[1:]:
        path = Path(p)
        data = path.read_bytes()
        if argv[0] == "fix":
            if fix_magic(path):
                print(f"fixed   {path}")
            else:
                print(f"ok      {path}")
        else:
            if has_raw_magic(data) and b"\r\n" not in data:
                print(f"ok      {path}")
            else:
                print(f"BAD     {path}  (UTF-8 magic or CRLF; run: python tools/slvs.py fix {path})")
                bad += 1
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
